### ISSUE TITLE
Positive net CO2 emissions at the end of the century

### ISSUE THREAD

**Issue by danielhuppmann** [My-Climate-Journey/climate-sustainability-investment-framework#3]
Per a discussion with Alexander Rickett in the MCJ Slack workspace...

I'm concerned about the statement in Principle 1 of reducing carbon dioxide emissions (you mean greenhouse gas in CO2-equivalent?) to 6 Gt in 2100 for two reasons.

1) Numerical modelling results: Recent literature suggests that emissions have to reach net-zero well before the end of the century to be in line with the Paris Agreement. Obviously, exact trajectories depend on numerous assumptions and model specifics, but the scientific consensus is quite clear. For a (relatively) recent overview, I refer to the table 2.SM.12 in the [IPCC SR15](https://www.ipcc.ch/sr15/chapter/chapter-2/) (Supplementary Material for Chapter 2).

Most scenarios staying below 2°C at the end of the century analyzed in the SR15 reach net-zero between 2040 and 2080 - only some scenarios that are as likely as not to stay below 2°C (Category Higher 2°C) do not reach net-zero before the end of the century. I think it's fair to say that "as likely as not" is not in line with the Paris Agreement of "well below" 2°C. 

Another assessment in the SR15 is given in Table 2.4, which shows ranges of CO2-only, CO2-from-energy, and Kyoto-GHG emissions in 2100. Again, only scenarios with a probability of 34-50% of staying below 2°C have positive values here.

The source code for the assessment is available (in rendered format) [here (Table 2.4)](https://data.ene.iiasa.ac.at/sr15_scenario_analysis/assessment/sr15_2.3.3_global_emissions_statistics.html) and [here (Table 2.SM.12)](https://data.ene.iiasa.ac.at/sr15_scenario_analysis/assessment/sr15_2.SM.4_geophysical_characteristics.html), links to the data and the notebook source are given at the top of the respective pages.

2) Framing: to stabilize temperature and stop (further) climate change, net GHG emissions have to reach zero (whether before or after 2100). Talking about reducing emissions to a still-positive value hides the challenge that we will need to completely eliminate (or continuously offset) GHG emissions.

**Comment by ketorickmo** [comment]
Daniel, thanks for the input, valuable indeed. I specially like the framing part. Net zero, other than being backed by recent literature, does indeed resonate stronger.  

"_Our target, in line with the 2°C cap stated above, is to drive annual emissions down from current 55 gigatons (GT) to **net zero** per year by 2100._"

We will also reference to the IPCC literature.
